/// Named C0 control codes from xterm's `EscapeSequences.ts`.
const Map<String, String> c0ControlCodes = <String, String>{
  'NUL': '\x00',
  'SOH': '\x01',
  'STX': '\x02',
  'ETX': '\x03',
  'EOT': '\x04',
  'ENQ': '\x05',
  'ACK': '\x06',
  'BEL': '\x07',
  'BS': '\x08',
  'HT': '\x09',
  'LF': '\x0a',
  'VT': '\x0b',
  'FF': '\x0c',
  'CR': '\x0d',
  'SO': '\x0e',
  'SI': '\x0f',
  'DLE': '\x10',
  'DC1': '\x11',
  'DC2': '\x12',
  'DC3': '\x13',
  'DC4': '\x14',
  'NAK': '\x15',
  'SYN': '\x16',
  'ETB': '\x17',
  'CAN': '\x18',
  'EM': '\x19',
  'SUB': '\x1a',
  'ESC': '\x1b',
  'FS': '\x1c',
  'GS': '\x1d',
  'RS': '\x1e',
  'US': '\x1f',
  'SP': '\x20',
  'DEL': '\x7f',
};

/// Named C1 control codes from xterm's `EscapeSequences.ts`.
const Map<String, String> c1ControlCodes = <String, String>{
  'PAD': '\x80',
  'HOP': '\x81',
  'BPH': '\x82',
  'NBH': '\x83',
  'IND': '\x84',
  'NEL': '\x85',
  'SSA': '\x86',
  'ESA': '\x87',
  'HTS': '\x88',
  'HTJ': '\x89',
  'VTS': '\x8a',
  'PLD': '\x8b',
  'PLU': '\x8c',
  'RI': '\x8d',
  'SS2': '\x8e',
  'SS3': '\x8f',
  'DCS': '\x90',
  'PU1': '\x91',
  'PU2': '\x92',
  'STS': '\x93',
  'CCH': '\x94',
  'MW': '\x95',
  'SPA': '\x96',
  'EPA': '\x97',
  'SOS': '\x98',
  'SGCI': '\x99',
  'SCI': '\x9a',
  'CSI': '\x9b',
  'ST': '\x9c',
  'OSC': '\x9d',
  'PM': '\x9e',
  'APC': '\x9f',
};

/// Seven-bit escaped form of the C1 string terminator.
const String c1EscapedStringTerminator = '\x1b\\';
